name: example
description: An example implementation for a SlidingSheet.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  charts_flutter: ^0.12.0
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  
  sliding_sheet2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/maps_screenshot.png